services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skeleton-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8001:80"
    depends_on:
      - pgsql
    networks:
      - laravel

  pgsql:
    image: postgres:latest
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8026:8025"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
