#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch is not in the pattern it should dominate... ${NC}"
    exit 1
fi

# For example, HEY-1: HEY-1: my resource
if [[ $COMMIT_MESSAGE == $ISSUE_ID* ]]; then
    exit 0
fi

# Format each changed file using Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
completed;

echo "$ISSUE_ID: $COMMIT_MESSAGE" >$1
