#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

# Regex for issue ID in branch name
REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")

# Check if ISSUE_ID was found
if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch is not in the pattern it should dominate... ${NC}"
    exit 1
fi

# Check if commit message starts with ISSUE_ID
if [[ $COMMIT_MESSAGE == $ISSUE_ID* ]]; then
    exit 0
fi

# Format each changed file using Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES; do
    ./vendor/bin/pint "${FILE}" > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo -e "${BRed}Error formatting file: ${FILE}${NC}"
        exit 1
    fi
    git add "${FILE}"
done

# Prefix commit message with ISSUE_ID
echo "$ISSUE_ID: $COMMIT_MESSAGE" > "$1"
